apiVersion: apps/v1
kind: Deployment
metadata:
  name: chandan-eta-deploy
  labels:
    app: chandan-eta-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chandan-eta-app
  template:
    metadata:
      labels:
        app: chandan-eta-app
    spec:
      containers:
      - name: chandan-eta-container
        image: chandan3461/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chandan-eta-np-service
  labels:
    app: chandan-eta-np-app
spec:
  selector:
    app: chandan-eta-deploy-lbl

  type: NodePort
  ports:
    port: 8080
    targetPort: 8080
